name: 'CI'

on:
  - 'push'
  - 'pull_request'

jobs:
  tests:
    name: 'Validate fixtures'

    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        php_version:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'

    steps:
      - name: 'Check out'
        uses: 'actions/checkout@v4'

      - name: 'Set up PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '${{ matrix.php_version }}'

      - name: 'Install dependencies'
        run: 'composer update'

      - run: 'php validate.php'
